<?php include_once 'header.php';?>

<div id="content-principal">
	<h2>Conceitos</h2>

	<p> Segundo o artigo 19 da Lei no 8.213, de 24 de julho de 1991, &quot;acidente do trabalho &eacute; o que ocorre pelo exerc&iacute;cio do
trabalho a servi&ccedil;o da empresa, ou pelo exerc&iacute;cio do trabalho do segurado especial, provocando les&atilde;o corporal ou perturba&ccedil;&atilde;o
funcional, de car&aacute;ter tempor&aacute;rio ou permanente&quot;. Pode causar desde um simples afastamento, a perda ou a redu&ccedil;&atilde;o da
capacidade para o trabalho, at&eacute; mesmo a morte do segurado. S&atilde;o eleg&iacute;veis aos benef&iacute;cios concedidos em raz&atilde;o da exist&ecirc;ncia
de incapacidade laborativa decorrente dos riscos ambientais do trabalho: o segurado empregado, o trabalhador avulso e o
segurado especial, no exerc&iacute;cio de suas atividades.</p>

	<p>Tamb&eacute;m s&atilde;o considerados como acidentes do trabalho: a) o acidente ocorrido no trajeto entre a resid&ecirc;ncia e o local de
trabalho do segurado; b) a doen&ccedil;a profissional, assim entendida a produzida ou desencadeada pelo exerc&iacute;cio do trabalho
peculiar a determinada atividade; e c) a doen&ccedil;a do trabalho, adquirida ou desencadeada em fun&ccedil;&atilde;o de condi&ccedil;&otilde;es especiais em
que o trabalho &eacute; realizado e com ele se relacione diretamente. Nestes dois &uacute;ltimos casos, a doen&ccedil;a deve constar da rela&ccedil;&atilde;o de
que trata o Anexo II do Regulamento da Previd&ecirc;ncia Social, aprovado pelo Decreto no 3.048, de 6/5/1999. Em caso excepcional,
constatando-se que a doen&ccedil;a n&atilde;o inclu&iacute;da na rela&ccedil;&atilde;o constante do Anexo II resultou de condi&ccedil;&otilde;es especiais em que o
trabalho &eacute; executado e com ele se relaciona diretamente, a Previd&ecirc;ncia Social deve equipar&aacute;-la a acidente do trabalho.
	</p>
	
	<h2>Tipos de Acidentes de Trabalho</h2>
	<ul>
		<li> <b>Acidentes Com CAT Registrada </b></li>
			<ul>
				<li> Correspondem ao n&uacute;mero de acidentes cuja Comunica&ccedil;&atilde;o de Acidentes do
	Trabalho &ndash; CAT foi registrada no INSS. N&atilde;o &eacute; contabilizado o rein&iacute;cio de tratamento ou afastamento por agravamento
	de les&atilde;o de acidente do trabalho ou doen&ccedil;a do trabalho, j&aacute; comunicado anteriormente ao INSS.</li>
			</ul>
		<li><b>Acidentes Sem CAT Registrada</b></li>
			<ul>
				<li>Correspondem ao n&uacute;mero de acidentes cuja Comunica&ccedil;&atilde;o de Acidentes do
Trabalho &ndash; CAT n&atilde;o foi registrada no INSS. O acidente &eacute; identificado por meio de um dos poss&iacute;veis nexos: Nexo T&eacute;cnico
Profissional/Trabalho, Nexo T&eacute;cnico Epidemiol&oacute;gico Previdenci&aacute;rio &ndash; NTEP ou Nexo T&eacute;cnico por Doen&ccedil;a Equiparada a
Acidente do Trabalho. Esta identifica&ccedil;&atilde;o &eacute; feita pela nova forma de concess&atilde;o de benef&iacute;cios acident&aacute;rios.
				 </li>
			</ul>
		<li><b>Acidentes T&iacute;picos</b></li>
			<ul>
				<li>S&atilde;o os acidentes decorrentes da caracter&iacute;stica da atividade profissional desempenhada pelo
segurado acidentado.</li>
			</ul>
		<li><b>Acidentes de Trajeto</b></li>
			<ul>
				<li>S&atilde;o os acidentes ocorridos no trajeto entre a resid&ecirc;ncia e o local de trabalho do segurado e
vice-versa.</li>
			</ul>
		<li><b>Doen&ccedil;a do trabalho</b></li>
			<ul>
				<li>S&atilde;o as doen&ccedil;as profissionais, aquelas produzidas ou desencadeadas pelo exerc&iacute;cio do trabalho
peculiar a determinado ramo de atividade conforme disposto no Anexo II do Regulamento da Previd&ecirc;ncia Social &ndash; RPS,
aprovado pelo Decreto no 3.048, de 6 de maio de 1999; e as doen&ccedil;as do trabalho, aquelas adquiridas ou desencadeadas em
fun&ccedil;&atilde;o de condi&ccedil;&otilde;es especiais em que o trabalho &eacute; realizado e com ele se relacione diretamente.</li>
			</ul>

	</ul>

</div>

<?php include_once 'footer.php';?>