<?php include_once 'header.php';?>


<?php
	$v_params = $this->getParams();
	$acidentesTrabalhoPorEstadoComTotaisPorAno = $v_params['acidentesTrabalhoPorEstadoComTotaisPorAno'];
	$acidentesTrabalhoPorCidadeComTotais = $v_params['acidentesTrabalhoPorCidadeComTotais'];
?>


<h2>Evolu&ccedil;&atilde;o AEAT nos estados</h2>

<form id="formFiltrar" action="index.php" method="post">

	<input type="hidden" name="controle" value="AcidenteTrabalho">
	<input type="hidden" name="acao" value="home">
	
	<?php include_once 'filtroEstado.php';?>
	
</form>


<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">

	google.load("visualization", "1", {packages:["corechart"]});	
      function drawVisualization() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable([
          ['Ano', 'Doencas', 'Tipicos', 'Trajetos', 'Outros', 'Obitos', 'Media'],

          <?php foreach ($acidentesTrabalhoPorEstadoComTotaisPorAno as $acidentesTrabalho) {?>
          		<?php 
          			$total = $acidentesTrabalho->getQuantidadeAcidenteDoenca() + $acidentesTrabalho->getQuantidadeAcidenteTipico() + $acidentesTrabalho->getQuantidadeAcidenteTrajeto() + $acidentesTrabalho->getQuantidadeAcidenteOutros() + $acidentesTrabalho->getQuantidadeObito();
					$media = $total/5;
          		?>
			<?php print "['". $acidentesTrabalho->getAno() . "' ," .   $acidentesTrabalho->getQuantidadeAcidenteDoenca() . "," . $acidentesTrabalho->getQuantidadeAcidenteTipico() . "," . $acidentesTrabalho->getQuantidadeAcidenteTrajeto() . "," . $acidentesTrabalho->getQuantidadeAcidenteOutros() . "," . $acidentesTrabalho->getQuantidadeObito() . "," . $media . "],"; ?>
          <?php } ?>

        ]);

		var title = 'Evolucao de acidentes/obitos no periodo de 2002 a 2009 no estado (<?php echo $_REQUEST['uf']; ?>)';
		
        var options = {
          title : title,
          vAxis: {title: "Quantitativos"},
          hAxis: {title: "Ano"},
          seriesType: "bars",
          series: {5: {type: "line"}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_divEstado'));
        chart.draw(data, options);
      }
      google.setOnLoadCallback(drawVisualization);
</script>

<div id="content-principal">
	<div id="chart_divEstado" style="width: 770px; height: 400px;"></div>
</div>

<?php include_once 'filtroPorCidade.php';?>

<script type="text/javascript">
 
      google.load('visualization', '1', {packages: ['corechart']});
      
      function drawVisualization() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable([
          ['Ano', 'Doencas', 'Tipicos', 'Trajetos', 'Outros', 'Obitos', 'Media'],

          <?php foreach ($acidentesTrabalhoPorCidadeComTotais as $acidentesTrabalho) {?>
          		<?php 
          			$total = $acidentesTrabalho->getQuantidadeAcidenteDoenca() + $acidentesTrabalho->getQuantidadeAcidenteTipico() + $acidentesTrabalho->getQuantidadeAcidenteTrajeto() + $acidentesTrabalho->getQuantidadeAcidenteOutros() + $acidentesTrabalho->getQuantidadeObito();
					$media = $total/5;
          		?>
			<?php print "['". $acidentesTrabalho->getAno() . "' ," .   $acidentesTrabalho->getQuantidadeAcidenteDoenca() . "," . $acidentesTrabalho->getQuantidadeAcidenteTipico() . "," . $acidentesTrabalho->getQuantidadeAcidenteTrajeto() . "," . $acidentesTrabalho->getQuantidadeAcidenteOutros() . "," . $acidentesTrabalho->getQuantidadeObito() . "," . $media . "],"; ?>
          <?php } ?>

        ]);

		var title = 'Evolucao de acidentes/obitos no periodo de 2002 a 2009 na cidade de <?php echo (isset($_REQUEST['cidade'])) ? $_REQUEST['cidade'] : ""; ?>';
		
        var options = {
          title : title,
          vAxis: {title: "Quantitativos"},
          hAxis: {title: "Ano"},
          seriesType: "bars",
          series: {5: {type: "line"}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_divCidade'));
        chart.draw(data, options);
      }
      google.setOnLoadCallback(drawVisualization);
      
    </script>

<div id="chart_divCidade" style="width: 770px; height: 400px;"></div>

<?php include_once 'footer.php';?>