<?php include_once 'header.php';?>

<div id="content-principal">
	<h3>Objetivo</h3>
	<p>Desenvolver uma aplica&ccedil;&atilde;o que facilite a pesquisa do usu&aacute;rio em
		obter informa&ccedil;&otilde;es a respeito da Quantidade de Acidentes de Trabalhos
		que ocorrem no Brasil.</p>

	<p>O Anu&aacute;rio Estat&iacute;stico de Acidentes de Trabalho - AEAT &eacute; um documento
		p&uacute;blico, com edi&ccedil;&atilde;o e publica&ccedil;&otilde;es anuais em meio papel e vers&atilde;o digital
		acess&iacute;vel por meio do s&iacute;tio do Minist&eacute;rio da Previd&ecirc;ncia Social.</p>

	<p>No caso deste trabalho, selecionamos infoma&ccedil;&otilde;es disponibilizadas na
		Se&ccedil;&atilde;o I subse&ccedil;&atilde;o D do Anu&aacute;rio, conte&uacute;do que trata de Comunica&ccedil;&atilde;o de
		Acidente de Trabalho (CAT), suas consequ&ecirc;ncias, por localiza&ccedil;&atilde;o
		geogr&aacute;fica das ocorr&ecirc;ncias (munic&iacute;pio) e seus respectivos
		quantitativos.</p>

	<p>As informa&ccedil;&otilde;es da Comunica&ccedil;&atilde;o de Acidente do Trabalho (CAT) t&ecirc;m
		origem nos registros dos benef&iacute;cios de natureza acident&aacute;ria concedidos
		pelo INSS.</p>
</div>

<?php include_once 'footer.php';?>