<?php
	$v_params = $this->getParams();
	$listaAcidentesTrabalho = $v_params['listaAcidentesTrabalho'];
	$listaEstados = $v_params['listaEstados']; 
?>

<?php include_once 'header.php';?>

<h2>Quantitativo de Acidentes/Obitos nos estados</h2>

<form id="formFiltrar" action="index.php" method="post">

	<input type="hidden" name="controle" value="AcidenteTrabalho">
	<input type="hidden" name="acao" value="listarAcidentesTrabalho">
	
	<?php include_once 'filtroAnoEstado.php';?>
	
</form>



<br />

<h2>Resultado da Pesquisa</h2>
<table border="1" id="myTable" class="dataTable display" cellspacing="0">
	<thead>
		<tr>
			<th>Codigo</th>
			<th>Nome</th>
			<th>UF</th>
			<th>Qtd. Obitos</th>
			<th>Qtd. Acid. Doen&ccedil;a</th>
			<th>Qtd. Acid. T&iacute;picos</th>
			<th>Qtd. Acid. Trajeto</th>
			<th>Qtd. Acid. Outros</th>
		</tr>
	</thead>
	
	<tfoot>
		<tr>
			<th>Codigo</th>
			<th>Nome</th>
			<th>UF</th>
			<th>Qtd. Obitos</th>
			<th>Qtd. Acid. Doen&ccedil;a</th>
			<th>Qtd. Acid. T&iacute;picos</th>
			<th>Qtd. Acid. Trajeto</th>
			<th>Qtd. Acid. Outros</th>
		</tr>
	</tfoot>
	
	<tbody>
		<?php
		foreach ($listaAcidentesTrabalho as $acidenteTrabalho) {
			?>
		<tr>
			<td>
				<?php echo $acidenteTrabalho->getCodigo(); ?>
			</td>
			<td>
				<?php echo $acidenteTrabalho->getNome(); ?>
			</td>
			<td>
				<?php echo $acidenteTrabalho->getUf(); ?>
			</td>
			
			<td class="center">
				<?php echo $acidenteTrabalho->getQuantidadeAcidenteDoenca(); ?>
			</td>
			<td class="center">
				<?php echo $acidenteTrabalho->getQuantidadeAcidenteTipico(); ?>
			</td>
			<td class="center">
				<?php echo $acidenteTrabalho->getQuantidadeAcidenteTrajeto(); ?>
			</td>
			<td class="center">
				<?php echo $acidenteTrabalho->getQuantidadeAcidenteOutros(); ?>
			</td>
			<td class="center">
				<?php echo $acidenteTrabalho->getQuantidadeObito(); ?>
			</td>		
		</tr>
		<?php
		}
		?>
	</tbody>
</table>

<?php include_once 'footer.php';?>
