<?php
	$v_params = $this->getParams();
	$acidentesTrabalhoPorEstadoComTotais = $v_params['acidentesTrabalhoPorEstadoComTotais'];
	$acidentesTrabalhoPorEstadoComTotaisPorAno = $v_params['acidentesTrabalhoPorEstadoComTotaisPorAno'];
	
	$listaCidades =  $v_params['listaCidades'];
?>

<?php include_once 'header.php';?>

<h2>Percentual de Acidentes/Obitos nos estados</h2>

<form id="formFiltrar" action="index.php" method="post">

	<input type="hidden" name="controle" value="AcidenteTrabalho"> 
	<input type="hidden" name="acao"     value="listarAcidentesTrabalhoPorEstadoComTotais">
	
	<?php include_once 'filtroAnoEstado.php';?>
	
</form>
<br />
<!--
<h2>Resultado da Pesquisa</h2>
<table border="1" id="myTable" class="dataTable display" cellspacing="0">
	<thead>
		<tr>
			<th>UF</th>
			<th>Qtd. Obitos</th>
			<th>Qtd. Acid. Doen&ccedil;a</th>
			<th>Qtd. Acid. T&iacute;picos</th>
			<th>Qtd. Acid. Trajeto</th>
			<th>Qtd. Acid. Outros</th>
		</tr>
	</thead>

	<tfoot>
		<tr>
			<th>UF</th>
			<th>Qtd. Obitos</th>
			<th>Qtd. Acid. Doen&ccedil;a</th>
			<th>Qtd. Acid. T&iacute;picos</th>
			<th>Qtd. Acid. Trajeto</th>
			<th>Qtd. Acid. Outros</th>
		</tr>
	</tfoot>

	<tbody>
		<tr>
			<td>
				<?php echo $acidentesTrabalhoPorEstadoComTotais->getUf(); ?>
			</td>

			<td class="center">
				<?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteDoenca(); ?>
			</td>
			<td class="center">
				<?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteTipico(); ?>
			</td>
			<td class="center">
				<?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteTrajeto(); ?>
			</td>
			<td class="center">
				<?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteOutros(); ?>
			</td>
			<td class="center">
				<?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeObito(); ?>
			</td>
		</tr>
	</tbody>
</table>
-->
				
<script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Estado',    '<?php echo $acidentesTrabalhoPorEstadoComTotais->getUf(); ?>'],
          ['Doenca',    <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteDoenca(); ?>],
          ['Tipico',    <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteTipico(); ?>],
          ['Trajeto',   <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteTrajeto(); ?>],
          ['Outros',    <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteOutros(); ?>],
          ['Obitos',    <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeObito(); ?>]
        ]);

        var title = "Totais de Acidentes / Obitos no Estado (<?php echo $acidentesTrabalhoPorEstadoComTotais->getUf(); ?>)";
        
        var options = {
          title: title,
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(data, options);
      }
</script>

<div id="piechart" style="height: 500px; text-align: center;"></div>


<!-- 
<button id="opEvolucao">Veja a Evolu&ccedil;&atilde;o</button>
 -->

<script type="text/javascript">

	google.load("visualization", "1", {packages:["corechart"]});
	google.setOnLoadCallback(drawVisualization);
      function drawVisualization() {
        // Some raw data (not necessarily accurate)
        var data = google.visualization.arrayToDataTable([
          ['Ano', 'Doencas', 'Tipicos', 'Trajetos', 'Outros', 'Obitos', 'Average'],

          <?php foreach ($acidentesTrabalhoPorEstadoComTotaisPorAno as $acidentesTrabalho) {?>
          		<?php 
          			$total = $acidentesTrabalho->getQuantidadeAcidenteDoenca() + $acidentesTrabalho->getQuantidadeAcidenteTipico() + $acidentesTrabalho->getQuantidadeAcidenteTrajeto() + $acidentesTrabalho->getQuantidadeAcidenteOutros() + $acidentesTrabalho->getQuantidadeObito();
					$media = $total/5;
          		?>
			<?php print "['". $acidentesTrabalho->getAno() . "' ," .   $acidentesTrabalho->getQuantidadeAcidenteDoenca() . "," . $acidentesTrabalho->getQuantidadeAcidenteTipico() . "," . $acidentesTrabalho->getQuantidadeAcidenteTrajeto() . "," . $acidentesTrabalho->getQuantidadeAcidenteOutros() . "," . $acidentesTrabalho->getQuantidadeObito() . "," . $media . "],"; ?>
          <?php } ?>

        ]);

		var title = 'Evolucao de acidentes ao no periodo de 2002 a 2009 no estado (<?php echo $_REQUEST['uf']; ?>)';
		
        var options = {
          title : title,
          vAxis: {title: "Quantitativos"},
          hAxis: {title: "Ano"},
          seriesType: "bars",
          series: {5: {type: "line"}}
        };

        var chart = new google.visualization.ComboChart(document.getElementById('chart_div1'));
        chart.draw(data, options);
      }
     
    </script>
    
<div id="evolucaoEstado">
	<h2>Evolu&ccedil;&atilde;o AEAT no periodo de 2002 a 2009</h2>
	
	<p>Veja toda a evolu&ccedil;&atilde;o dos acidendes de trabalho no periodo de 2002 a 2009 referente ao estado da <?php echo $acidentesTrabalhoPorEstadoComTotais->getUf(); ?>
	</p>

	<div id="chart_div1"></div>
</div>

<br /><br />
<div style="clear:both; height: 50px;"></div>
<?php include_once 'filtroPorCidade.php';?>

<?php include_once 'footer.php';?>
