<?php
	$v_params = $this->getParams();
	$acidentesTrabalhoPorEstadoComTotais = $v_params['acidentesTrabalhoPorEstadoComTotais'];
	$acidentesTrabalhoPorEstadoComTotaisPorAno = $v_params['acidentesTrabalhoPorEstadoComTotaisPorAno'];
	
	$listaCidades =  $v_params['listaCidades'];
?>

<?php include_once 'header.php';?>

<h2>Percentual de Acidentes/Obitos nos estados</h2>

<form id="formFiltrar" action="index.php" method="post">

	<input type="hidden" name="controle" value="AcidenteTrabalho"> 
	<input type="hidden" name="acao"     value="listarAcidentesTrabalhoPorEstadoComTotais">
	
	<?php include_once 'filtroAnoEstado.php';?>
	
</form>
<br />
<!--
<h2>Resultado da Pesquisa</h2>
<table border="1" id="myTable" class="dataTable display" cellspacing="0">
	<thead>
		<tr>
			<th>UF</th>
			<th>Qtd. Obitos</th>
			<th>Qtd. Acid. Doen&ccedil;a</th>
			<th>Qtd. Acid. T&iacute;picos</th>
			<th>Qtd. Acid. Trajeto</th>
			<th>Qtd. Acid. Outros</th>
		</tr>
	</thead>

	<tfoot>
		<tr>
			<th>UF</th>
			<th>Qtd. Obitos</th>
			<th>Qtd. Acid. Doen&ccedil;a</th>
			<th>Qtd. Acid. T&iacute;picos</th>
			<th>Qtd. Acid. Trajeto</th>
			<th>Qtd. Acid. Outros</th>
		</tr>
	</tfoot>

	<tbody>
		<tr>
			<td>
				<?php //echo $acidentesTrabalhoPorEstadoComTotais->getUf(); ?>
			</td>

			<td class="center">
				<?php //echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteDoenca(); ?>
			</td>
			<td class="center">
				<?php //echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteTipico(); ?>
			</td>
			<td class="center">
				<?php //echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteTrajeto(); ?>
			</td>
			<td class="center">
				<?php //echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteOutros(); ?>
			</td>
			<td class="center">
				<?php //echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeObito(); ?>
			</td>
		</tr>
	</tbody>
</table>
-->
				
<script type="text/javascript">
      google.load("visualization", "1", {packages:["corechart"]});
      google.setOnLoadCallback(drawChart);
      function drawChart() {
        var data = google.visualization.arrayToDataTable([
          ['Estado',    '<?php echo $acidentesTrabalhoPorEstadoComTotais->getUf(); ?>'],
          ['Doenca',    <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteDoenca(); ?>],
          ['Tipico',    <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteTipico(); ?>],
          ['Trajeto',   <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteTrajeto(); ?>],
          ['Outros',    <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeAcidenteOutros(); ?>],
          ['Obitos',    <?php echo $acidentesTrabalhoPorEstadoComTotais->getQuantidadeObito(); ?>]
        ]);

        var title = "Totais de Acidentes / Obitos no Estado (<?php echo $acidentesTrabalhoPorEstadoComTotais->getUf(); ?>)";
        
        var options = {
          title: title,
          is3D: true,
        };

        var chart = new google.visualization.PieChart(document.getElementById('piechart'));
        chart.draw(data, options);
      }
</script>

<div id="piechart" style="height: 500px; text-align: center;"></div>

<div id="evolucaoEstado">
	<h2>Evolu&ccedil;&atilde;o AEAT no periodo de 2002 a 2009</h2>
	
	<p>Veja toda a evolu&ccedil;&atilde;o dos acidendes de trabalho no periodo de 2002 a 2009 referente ao estado da <?php echo $acidentesTrabalhoPorEstadoComTotais->getUf(); ?>, clicando no link abaixo:
	</p>
	
	<div class="button-visualizar">
	<input type="button" id="opEvolucao" value="Visualizar" />
	</div>
	<div id="chart_div"></div>
</div>

<br /><br /><br />
<div style="clear:both;"></div>
<?php include_once 'filtroPorCidade.php';?>

<?php include_once 'footer.php';?>

<div class="testeGrafico"></div>
