<?php
$v_params = $this->getParams();
$v_municipios = $v_params['v_municipios'];
?>

<?php include_once 'header.php';?>

<table border="1">
	<tr>
		<th>Codigo</th>
		<th>Nome</th>
		<th>UF</th>
		<th colspan="3">A&ccedil;&otilde;es</th>
	</tr>
	<?php
	foreach ($v_municipios as $o_municipio) {
		?>
	<tr>
		<td>
			<?php echo $o_municipio->getCodigo(); ?>
		</td>
		<td>
			<?php echo $o_municipio->getNome(); ?>
		</td>
		<td>
			<?php echo $o_municipio->getUf(); ?>
		</td>
		<td align="center"><a
			href='?controle=Telefone&acao=listarTelefones&in_con=<?php echo $o_municipio->getCodigo(); ?>'>Telefones</a>
			<a
			href='?controle=Contato&acao=manterContato&in_con=<?php echo $o_municipio->getCodigo(); ?>'>Editar</a>
			<a
			href='?controle=Contato&acao=apagarContato&in_con=<?php echo $o_municipio->getCodigo(); ?>'>Apagar</a>
		</td>
	</tr>
	<?php
	}
	?>
</table>

<?php include_once 'footer.php';?>
